export const Type = {
  FILTER_CONTACT: "FILTER_CONTACT",

  GET_CONTACTS_START: "GET_CONTACTS_START",
  GET_CONTACTS_SUCCESS: "GET_CONTACTS_SUCCES",
  GET_CONTACTS_ERROR: "GET_CONTACTS_ERROR",

  POST_CONTACT_START: "POST_CONTACT_START",
  POST_CONTACT_SUCCESS: "POST_CONTACT_SUCCESS",
  POST_CONTACT_ERROR: "POST_CONTACT_ERROR",
  
  DELETE_CONTACT_START: "DELETE_CONTACT_START",
  DELETE_CONTACT_SUCESS: "DELETE_CONTACT_SUCESS",
  DELETE_CONTACT_ERROR: "DELETE_CONTACT_ERROR",
};